<?php
    module_load_include('inc', 'banrep_promoted', 'banrep_promoted');


    /**
     * Implements hook_cron();
    */
    function banrep_promoted_cron(){
        
        _verificate_users_requiremets_completed();

    }


    /**
* Implements hook_mail().
*/
function banrep_promoted_mail($key, &$message, $params) {
    $language = $message['language'];

    $variables = array(
        '!sitename' => variable_get('site_name', 'Drupal'),
        '!user' => $params['user']->name->value()
    );

    switch ($key) {
        case 'user_promoted':
            $message['subject'] = t('Solicitud recibida desde [!sitename]',
            $variables, array('langcode' => $language->language));
            $message['body'][] = t("Recuerda tus datos de acceso:");
            break;
        
        default:
            # code...
            break;
    }


   }