<?php

function banrep_seminary_menu() {
    $items = array();

    $items['seminarios-new'] = array(
        'title' => t('Seminarios'),
        'page callback' => 'banrep_seminary_page',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    $items['crear-evento'] = array(
      'title' => t('Crear nuevo evento'),
      //'page callback' => 'drupal_get_form', 
      'page callback' => 'event_page', 
      //'page arguments' => array('event_form'), 
      //'access callback' => 'user_access',
      'access callback' => TRUE,
      //'access arguments' => array('access create_event_content'),
  );

    return $items;
}

function banrep_seminary_theme() {
  return array(
    'seminary' => array(
      'variables' => array(
        'events' => NULL,
        'texts' => NULL,
        'images' => NULL,
        'cities' => NULL,
        'city' => NULL,
      ),
      'template' => 'templates/banrep_seminary',
    ),
    'create_event' => array(
      'variables' => array(
        'form' => NULL,
      ),
      'template' => 'templates/create_event',
    ),
  );
}

function banrep_seminary_page() {
  $events = '';
  $texts = '';
  $images = '';
  $cities = getCities();
  
  return theme(
    'seminary',
    [
      'events' => $events,
      'texts' => $texts,
      'images' => $images,
      'cities' => $cities,
      'city' => '',
    ]
  );
}

function city_form($form, &$form_state) {
  //$form['#attributes']['method'][] = 'GET';
  $form['cities'] = array(
    '#type' => 'select',
    '#title' => 'Ciudad',
    "#empty_option"=> '- Seleccione una ciudad -',
    '#options' => getCities(),
    '#attributes' => array(
      'onChange' => 'this.form.submit();',
    ),
  );

  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => 'Filtrar',
    '#ajax' => array(
      'callback' => 'buscador_form_submit_callback',
      'wrapper' => 'box',
      'effect' => 'fade'
    ),
    '#attributes' => array(
      'class' => array('js-hide'),
    ),
  );

  $form['box-container'] = array(
    '#prefix' => '<div id="box">',
    '#suffix' => '</div>',
  );

  return $form;
}

function city_form_submit($form, &$form_state) {
  $form_state['rebuild'] = TRUE;
}

function contact_form($form, &$form_state, $vars) {
  if (!empty($form_state['response'])) {
    $form['response'] = array('#markup' => $form_state['response']);
  }
  $form['ciudad'] = array(
      '#type' => 'hidden',
  );
  $form['nombre'] = array(
      '#type' => 'textfield',
      '#title' => 'Nombre',
  );
  $form['afiliacion'] = array(
      '#type' => 'textfield',
      '#title' => 'Afiliación institucional',
  );
  $form['tema'] = array(
      '#type' => 'textfield',
      '#title' => 'Título o tema de la presentación',
  );
  $form['correo'] = array(
      '#type' => 'emailfield',
      '#title' => 'Correo electrónico',
      '#attributes' => array(
        'required' => 'required',
      ),
  );
  $form['correo_seminario'] = array(
      '#type' => 'hidden',
      '#title' => 'Correo ciudad',
      '#value' => !empty($vars['email']) ? $vars['email'] : '',
  );
  $form['file'] = array(
      '#type' => 'file',
      '#title' => 'Adjuntar documento',
      //'#description' => 'Extensiones permitidas: pdf, doc, docx, zip, rar',
      '#attributes' => array(),
  );
  
  $form['policy'] = array(
    '#type' => 'markup',
    '#markup' => '<div class="seminary-policy">
      <p>
        <b>IMPORTANTE - Autorización de tratamiento de datos personales:</b> Mediante el diligenciamiento y registro de sus datos 
        personales usted autoriza al BANCO DE LA REPÚBLICA el tratamiento (recolección, almacenamiento, uso, circulación o 
        supresión) de todos los datos que nos suministra en el presente formato con la finalidad de adelantar la postulación 
        de su trabajo para ser evaluado, llevar registro de su postulación, así como para la construcción de indicadores y 
        estadísticas para el seguimiento y control del la inscripción de trabajos; y, en todo caso, dentro de sus funciones 
        constitucionales y legales.

        Para tal efecto, el BANCO DE LA REPÚBLICA informa que:
      </p>
      <ol>
        <li>
          El tratamiento de los datos personales se realizará de acuerdo con las políticas o lineamientos generales; 
          así como las políticas de seguridad de la información, disponibles en la sección 
          <a href="http://www.banrep.gov.co/proteccion-datos-personales" target="_blank">"Protección de Datos Personales - Habeas Data"</a>, 
          disponibles desde el 18 de junio de 2013.
        </li>
        <li>
          El titular de los datos personales podrá acceder, conocer, actualizar y rectificar dichos datos; ser informado 
          del uso dado a los mismos; presentar consultas y reclamos sobre el manejo de dichos datos; revocar esta 
          autorización o solicitar la supresión de los datos, en los casos en que sea procedente, y los demás derechos 
          que le confiere la Ley.
        </li>
        <li>
          Para ejercer tales derechos, podrá contactarse a través del 
          <a href="http://www.banrep.gov.co/es/atencion-ciudadano" target="_blank">Sistema de Atención al Ciudadano (SAC)</a>.
        </li>
      </ol>
    </div>'
  );
  
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Enviar',
    '#ajax' => array(
      'callback' => 'contact_form_submit_callback',
      'wrapper' => 'box',
      'effect' => 'fade'
    )
  );

  $form['box-container'] = array(
    '#prefix' => '<div id="box">',
    '#suffix' => '</div>',
  );
  
  return $form;
}

function contact_form_submit_callback($form, &$form_state) {
  $body = array("
    Gracias por contactarse con nosotros

    Su solicitud será evaluada y pronto recibirá una respuesta.

    Banco de la república.
  ");
  $from = "pvillate@dayscript.com";
  $to = $form_state['values']['correo_seminario'];
  //$to = 'pvillate@dayscript.com';
  $file = $_FILES['files'];

  if($file['tmp_name']['file'] != '') {
    $attachment = array(
      'path' => $file['tmp_name']['file'],
      'filecontent' => file_get_contents($file['tmp_name']['file']),
      'filename' => $file['name']['file'],
      'mime' => $file['type']['file'],
      'encoding' => 'base64',
      'disposition' => 'attachment',
      'list' => TRUE,
    );
  }
  $params = array(
    'subject' => 'Envío de formulario en seccion de seminarios',
    'body' => $body,
    'attachments' => array(0 => $attachment)
  );

  $sent = drupal_mail('banrep_seminary', 'contact', $to, language_default(), $params, $from, true);
  
  if ($sent['result']) {
    drupal_set_message(t('Your message has been sent.'));
    //drupal_goto('seminarios-new');
    //drupal_exit();
    $commands[] = array('command' => 'reloadPage');
	  return array('#type' => 'ajax', '#commands' => $commands);
  } else {
    drupal_set_message(t('There was a problem sending your message and it was not sent.'), 'error');
  }
  /*$form_state['rebuild'] = TRUE;
  $element = $form['box-container'];
  $element['#markup'] = 'Formulario enviado';
  return $element;*/
}

function event_page($form, &$form_state) {
  module_load_include('inc', 'node', 'node.pages');

  $form = node_add('event');

  return theme(
    'create_event',
    [
      'form' => $form,
    ]
  );
}
function event_form_submit($form, &$form_state) {
}

function banrep_seminary_mail($key, &$message, $params){
  switch ($key){
    case 'contact':
      /*$message['headers']['MIME-Version'] = '1.0';
      $message['headers']['Content-Type'] = 'multipart/mixed; text/html; charset=UTF-8'; */
      $message['subject'] = $params['subject'];
      $message['body'] = $params['body'];
      if (isset($params['attachment'])) {
        $message['params']['attachments'][] = $params['attachment'];
      }
      break;
  }
}

function banrep_seminary_preprocess(&$variables) {
  $variables['city_form'] = drupal_get_form('city_form');
  try {
    $tid = $variables['city_form']['cities']['#value'];
    if(!empty($tid)) {
      $term = entity_metadata_wrapper('taxonomy_term', $tid);
      $name = $term->name->value();
      $texts = array();
      $images = array();
      $events = array();
      $cities = getCities();
      $texts['text-a'] = $term->field_texto_a->value();
      $texts['text-b'] = $term->field_texto_b->value();
      $images['first'] = $term->field_imagen_uno->value();
      $images['second'] = $term->field_imagen_dos->value();
      $variables['texts'] = $texts;
      $variables['city'] = $tid;
      $variables['images'] = $images;
      $variables['name'] = $name;
      $variables['email'] = $term->field_correo_ciudad->value();
      drupal_set_title("Seminarios en $name", CHECK_PLAIN);
      $variables['contact_form'] = drupal_get_form('contact_form',  ['email' => $term->field_correo_ciudad->value()]);
    }
  } catch (EntityMetadataWrapperException $e) {
    watchdog('seminarios', 'Error al procesar elección de ciudad: '.$e);
  }
}

function banrep_seminary_node_view($node, $view_mode = 'full', $langcode = NULL) {
  if($view_mode == 'full'){
    $node->content['field_inscripcion'] = array(
        '#markup' => '<div class="field field-name-field-inscripcion">
            <a href="/registro-seminario?nid='.$node->nid.'" class="btn btn-warning">Inscripciones</a>
          </div>'
    );
  }
}

function getCities() {
  $cities = array();
  $vocabulary = taxonomy_vocabulary_machine_name_load('ciudades_seminarios');
  $vtree = taxonomy_get_tree($vocabulary->vid);
  foreach ($vtree AS $term) {
    $cities[$term->tid] = $term->name;
  }
  return $cities;
}


