<?php

/**
 * @file
 * Funcionalidades relacionadas a sección CAIE.
 */

/**
 * Implements hook_preprocess().
 */
function banrep_caie_preprocess_page(&$variables, $hook) {
  if(arg(0) == 'node' && arg(1) == 8555){
    drupal_add_js(drupal_get_path('module', 'banrep_caie') . '/js/caie_servicios.js');
  }
}

/**
 * Implements hook_menu().
 */
function banrep_caie_menu() {
  $items['caie'] = array(
    'title' => 'CAIE',
    'page callback' => 'banrep_caie_page',
    'page arguments' => array(),
    'access callback' => TRUE,
    'file' => 'banrep_caie.pages.inc',
    'type' => MENU_CALLBACK,
  );

  $items['dashboard'] = array(
    'title' => '',
    'page callback' => 'banrep_caie_dashboard_page',
    'page arguments' => array(),
    'access callback' => 'user_is_logged_in',
    'file' => 'banrep_caie.pages.inc',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_webform_select_options_info().
 */
function banrep_core_webform_select_options_info() {
  $items = array();
  $items['soluciones_caie_servicios'] = array(
    'title' => t('Soluciones CAIE - Servicios'),
    'options callback' => 'webform_options_soluciones_caie_servicios',
  );
  return $items;
}

/**
 * Webform options info callback.
 */
function webform_options_soluciones_caie_servicios() {
  module_load_include('inc', 'banrep_caie', 'banrep_caie.functions');
  $query = db_select('field_data_field_titulo','t')->distinct();
  $query->condition('t.bundle', 'field_portafolio_servicios');
  $query->condition('t.entity_type', 'field_collection_item');
  $query->fields('t', array('field_titulo_value'));
  $services = $query->execute()->fetchCol();
  $options = array();
  if (!empty($services) && is_array($services)) {
    foreach ($services as $key => $service_name) {
      $machine_name = human_to_machine($service_name);
      $options[$machine_name] = $service_name;
    }
  }
  return $options;
}
