<?php

/**
 * Implements hook_preprocess().
 */
function banrep_caie_preprocess_page(&$variables, $hook) {
  if(arg(0) == 'node' && arg(1) == 8555){
    drupal_add_js(drupal_get_path('module', 'banrep_caie') . '/js/caie_servicios.js');
  }
}
/**
 * Implements hook_menu().
 */
function banrep_caie_menu() {
  $items['caie'] = array(
    'title' => 'CAIE',
    'page callback' => 'banrep_caie_page',
    'page arguments' => array(),
    'access callback' => TRUE,
    'file' => 'banrep_caie.pages.inc',
    'type' => MENU_CALLBACK,
  );

  return $items;
}
/**
 * Implements hook_block_info().
 */
function banrep_caie_block_info() {
  $blocks['caie_shortcuts'] = array(
    'info' => t('Gestionar Portal'),
    'cache' => DRUPAL_NO_CACHE
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function banrep_caie_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'caie_shortcuts':
      $output = '
      <ul>
        <li><a href="/es/admin/content/clasificacion-jel">Códigos JEL</a></li>
        <li><a href="/es/admin/content/gestionar-conceptos">Conceptos</a></li>
        <li><a href="/es/admin/content/gestionar-publicaciones">Publicaciones</a></li>
        <li><a href="/es/admin/content/gestionar-recursos">Recursos</a></li>
        <li><a href="/es/admin/content/gestionar-seminarios">Seminarios</a></li>
        <li><a href="/es/admin/people/gestionar-investigadores">Investigadores</a></li>
      </ul>
      ';
      $block['subject'] = t('');
      $block['content'] = drupal_get_form('caie_form_1');
      break;

  }
  return $block;
}
